소셜 로그인 모달창 구현
Step3-kakao-tech-campus/Team4_FE pull request #11
Opened 2023-10-01 08:32 UTC by coririri

### 작업 내용
___

- 구글, 카카오 소셜 로그인 가이드 라인에 맞게 버튼 디자인
- 구글, 카카오 소셜 로그인 버튼 클릭 시 백앤드에서 제공한 리다이렉트 링크로 이동
- 리액트 모달 라이브러리를 이용해 모달창 구현
![bandicam 2023-10-01 17-30-06-981](https://github.com/Step3-kakao-tech-campus/Team4_FE/assets/87762581/f636222f-ebe1-49d3-a920-de3a1d7283d4)

### 그 외 변경 사항
___
- eslint에서 'onCloseModalClick' is missing in props validation  react/prop-types 오류가 발생해   "react/prop-types": "off" 꺼둔 상태
- react-modal 라이브러리 설치

2023-10-02 08:04 UTC, HENOZIWD requested changes

2023-10-02 08:04 UTC, HENOZIWD commented on src/components/organisms/socialLoginModalContent.jsx
> +    <div className="text-center mt-12 relatie">
`relative` 오타 있습니다!

2023-10-02 08:04 UTC, HENOZIWD commented on src/components/organisms/socialLoginModalContent.jsx
> +        <a href="http://localhost:8080/oauth2/authorization/Google" className="flex items-center justify-center bg-white w-[250px] h-[40px] shadow-md rounded-xl kakao-button mb-2">
`kakao-button` 클래스의 역할은 무엇인가요? 쓰이지 않는 클래스라면 사용하지 않는 것이 좋아 보입니다

2023-10-02 08:04 UTC, HENOZIWD commented on src/components/organisms/socialLoginModalContent.jsx
> +          <span className="ml-4 text-6 font-roboto">Sign in with Google</span>
`text-6`은 tailwindcss에는 없는 클래스인데 어떤 의도로 작성하신건가요?

2023-10-03 09:02 UTC, coririri commented on src/components/organisms/socialLoginModalContent.jsx
> +    <div className="text-center mt-12 relatie">
오타 수정 했습니다!

2023-10-03 09:02 UTC, coririri commented on src/components/organisms/socialLoginModalContent.jsx
> +        <a href="http://localhost:8080/oauth2/authorization/Google" className="flex items-center justify-center bg-white w-[250px] h-[40px] shadow-md rounded-xl kakao-button mb-2">
클래스 삭제 했습니다 (초기 작업 때 알아보기 쉬울려고 넣었습니다)

2023-10-03 09:04 UTC, coririri commented on src/components/organisms/socialLoginModalContent.jsx
> +          <span className="ml-4 text-6 font-roboto">Sign in with Google</span>
text-md로 수정 했습니다

2023-10-03 11:26 UTC, HENOZIWD approved these changes

2023-10-04 03:11 UTC, merged