유저 정보 수정 페이지 구현
Step3-kakao-tech-campus/Team4_FE pull request #75
Opened 2023-10-22 12:22 UTC by coririri

## 구현 내용
![bandicam 2023-10-22 21-19-38-258](https://github.com/Step3-kakao-tech-campus/Team4_FE/assets/87762581/83abb870-2dfa-418e-91c4-c811d796550e)

- UI는 드롭다운을 통해서 언어와 성별을 선택하고, 이미지는 따로 업로드 해 수정하도록 구현 하였습니다.
- change 클릭시 닉네임, 언어, 성별만 수정  (이미지는 이미지 수정 버튼을 통해 수정 요청)
- 리덕스 저장소에 닉네임, 언어, 성별, 유저이미지를 저장하였습니다. 
- S3 관련 개발은 백앤드와 조율 후 구현 다시 하겠습니다.

2023-10-22 13:01 UTC, HENOZIWD requested changes

2023-10-22 13:01 UTC, HENOZIWD commented on src/store/store.ts
> +export type AppDispatch = typeof store.dispatch;
이 파일 저는 src/store/index.ts로 만들어놨는데 하나로 통일하는게 좋아 보여요 어떤 걸로 하실래요?

2023-10-22 13:51 UTC, coririri commented on src/store/store.ts
> +export type AppDispatch = typeof store.dispatch;
index.ts로 만들어두면 될꺼같네요! 제가 통합할 때 수정해두겠습니다

2023-10-24 05:39 UTC, HENOZIWD approved these changes

2023-10-26 08:34 UTC, merged