소셜 로그인 기능 구현
Step3-kakao-tech-campus/Team4_FE pull request #91
Opened 2023-11-03 05:07 UTC by coririri

## 백앤드와의 협의 내용
- 프론트측에서 백앤드가 제공한 링크로 사용자를 리다이렉트 시킨다
- 사용자가 소셜 로그인 과정을 진행 한다
- 백앤드가 사용자를 다시 리다이렉트 시킨다 (배포주소/login-redirect)
- 해당 리 다이렉트 url에 쿼리로 isFristLogin, accessToken, refreshToken, accessTokenExpiresIn를 전달해준다.

## 구현 내용
- LoginRedirect 컴포넌트에서 각 토큰과 만료시간을 localStroage에 저장한다.
- 유저가 첫 로그인이라면 회원가입 추가정보 입력 페이지로 리다이렉트 시키고, 기존 유저라면 소셜 로그인 모달창을 열었던 곳으로 리다이렉트 시킨다. 
- instance의 요청을 intercept해서 헤더값에 토큰을 포함시킨다.
- 만료시간이 초과 됐다면 새로운 토큰을 발급한다.

2023-11-03 05:28 UTC, coririri commented
오류해결하고 pr 업데이트할게요!

2023-11-03 13:44 UTC, HENOZIWD approved these changes

2023-11-03 13:46 UTC, HENOZIWD requested changes

2023-11-03 13:46 UTC, HENOZIWD commented on src/components/page/loginRedriect.tsx
> +      navigate(localStorage.getItem('previouseUrl') || '/');
회원 정보 입력 페이지로 이동하는 로직이 빠진 것 같아요.

2023-11-04 02:21 UTC, coririri commented on src/components/page/loginRedriect.tsx
> +      navigate(localStorage.getItem('previouseUrl') || '/');
추가 했습니다!

2023-11-04 04:54 UTC, HENOZIWD approved these changes

2023-11-04 08:07 UTC, merged